# Project Name
TARGET = ShimReverb

# Sources
CPP_SOURCES = ShimReverb.cpp dsp/ShimmerReverb.cpp  ../daisy_saul.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
