# Project Name
TARGET = test2

APP_TYPE = BOOT_SRAM

# Sources
CPP_SOURCES = test2.cpp ../daisy_varga.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile