# Project Name
TARGET = codectest

# Build Project for Daisy Bootloader
#APP_TYPE = BOOT_SRAM

# Sources
CPP_SOURCES = codectest.cpp ../daisy_patch_3060.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

