# Project Name
TARGET = pluckecho

#USE_FATFS = 1

#DEBUG = 1
#LDFLAGS += -u _printf_float

#APP_TYPE = BOOT_QSPI

# Sources
CPP_SOURCES = pluckecho.cpp ../daisy_hank.cpp ../switch_hank.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

