# Project Name
TARGET = Test

DEBUG = 1
USE_FATFS = 0

# Sources
CPP_SOURCES = Test.cpp LedMatrix.cpp sr_595.cpp ../daisy_saul.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile