# Project Name
TARGET = hwtest

 #DEBUG = 1
 #LDFLAGS += -u _printf_float

# Sources
CPP_SOURCES = hwtest.cpp ../daisy_hank.cpp ../switch_hank.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

