# Project Name
TARGET = Lfo

 #DEBUG = 1
 #LDFLAGS += -u _printf_float

# Sources
CPP_SOURCES = Lfo.cpp ../daisy_white.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

