# Project Name
TARGET = modres

 #DEBUG = 1
 #LDFLAGS += -u _printf_float
 #APP_TYPE = BOOT_NONE
 #USE_FATFS = 1

#APP_TYPE = BOOT_NONE

# Sources
CPP_SOURCES = modres.cpp  ../daisy_white.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core

#GCC_PATH = /data/nucleo/gcc-arm-none-eabi-10-2020-q4-major/bin/

include $(SYSTEM_FILES_DIR)/Makefile

