# Project Name
TARGET = test

USE_FATFS = 1

# Sources
CPP_SOURCES = test.cpp wavplayer2.cpp ../daisy_white.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
